import React, { useState } from 'react';
import { FileText, Download, Filter as FilterIcon, Calendar, User, CheckCircle2, Clock, ShieldCheck } from 'lucide-react';
import { Breadcrumb, Button, Card, CardBody, Table, TableHeader, TableBody, TableRow, TableCell, Badge, Select, Input, KPICard } from '../../components/ui';
import { useToast } from '../../context/ToastContext';

const reportsList = [
  { id: 'REP-101', title: 'Q1 Enterprise Revenue & MRR Audit', category: 'Finance', user: 'Alexander Wright', date: '2026-02-25', status: 'Approved', format: 'CSV / PDF' },
  { id: 'REP-102', title: 'Sales Pipeline & Opportunity Conversion', category: 'Sales', user: 'Sarah Jenkins', date: '2026-02-24', status: 'Approved', format: 'CSV' },
  { id: 'REP-103', title: 'Lead Source Attribution & ROI Analysis', category: 'Marketing', user: 'David Chen', date: '2026-02-22', status: 'Approved', format: 'CSV' },
  { id: 'REP-104', title: 'ERP Procurement & Inventory Valuation', category: 'Operations', user: 'Alexander Wright', date: '2026-02-20', status: 'Pending Review', format: 'CSV / PDF' },
  { id: 'REP-105', title: 'Customer Support SLA & CSAT Performance', category: 'Support', user: 'Elena Rostova', date: '2026-02-18', status: 'Approved', format: 'CSV' },
];

export const CrmReports = () => {
  const { addToast } = useToast();

  const [categoryFilter, setCategoryFilter] = useState('all');
  const [userFilter, setUserFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');

  const filteredReports = reportsList.filter((r) => {
    const matchCategory = categoryFilter === 'all' || r.category === categoryFilter;
    const matchUser = userFilter === 'all' || r.user === userFilter;
    const matchStatus = statusFilter === 'all' || r.status === statusFilter;
    return matchCategory && matchUser && matchStatus;
  });

  const handleExportCSV = (reportTitle) => {
    // Generate CSV string
    const csvHeader = 'Report ID,Title,Category,Generated By,Date,Status\n';
    const csvRows = filteredReports
      .map((r) => `"${r.id}","${r.title}","${r.category}","${r.user}","${r.date}","${r.status}"`)
      .join('\n');
    const csvContent = 'data:text/csv;charset=utf-8,' + encodeURIComponent(csvHeader + csvRows);

    const downloadLink = document.createElement('a');
    downloadLink.setAttribute('href', csvContent);
    downloadLink.setAttribute('download', `${reportTitle.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);

    addToast({ title: 'CSV Downloaded', message: `Exported ${reportTitle} to CSV format.`, type: 'success' });
  };

  return (
    <div className="flex flex-col gap-6" style={{ width: '100%', maxWidth: '100%', boxSizing: 'border-box' }}>
      {/* 1. Header */}
      <div className="page-header-row">
        <div>
          <Breadcrumb items={[{ label: 'CRM nErgy' }, { label: 'Reports Hub' }]} />
          <h1
            style={{
              fontSize: '24px',
              fontWeight: 800,
              color: 'var(--text-primary)',
              margin: '2px 0 0 0',
              fontFamily: 'var(--font-display)',
              letterSpacing: '-0.02em',
            }}
          >
            Enterprise Reports Repository
          </h1>
          <p className="text-xs text-secondary margin-0" style={{ marginTop: '2px' }}>
            Generate, filter, and export system audit reports in CSV and PDF formats.
          </p>
        </div>

        {/* Green Export All CSV Button */}
        <div className="header-actions-right">
          <Button
            variant="primary"
            size="sm"
            icon={Download}
            onClick={() => handleExportCSV('All_CRM_Reports_Summary')}
            style={{ backgroundColor: '#16a34a', borderColor: '#16a34a', color: '#ffffff' }}
          >
            Export All (CSV)
          </Button>
        </div>
      </div>

      {/* 2. Top Summary KPI Cards Strip */}
      <div className="grid-responsive-kpi">
        <KPICard
          title="TOTAL AUDIT REPORTS"
          value={`${reportsList.length}`}
          change="100% Synced"
          changeType="positive"
          changePeriod="system records"
          icon={FileText}
          iconBg="rgba(29, 78, 216, 0.1)"
          iconColor="#1d4ed8"
        />
        <KPICard
          title="APPROVED REPORTS"
          value={`${reportsList.filter((r) => r.status === 'Approved').length}`}
          change="80% Verified"
          changeType="positive"
          changePeriod="compliance passed"
          icon={CheckCircle2}
          iconBg="rgba(22, 163, 74, 0.1)"
          iconColor="#16a34a"
        />
        <KPICard
          title="PENDING REVIEW"
          value={`${reportsList.filter((r) => r.status === 'Pending Review').length}`}
          change="1 In Review"
          changeType="neutral"
          changePeriod="auditor queue"
          icon={Clock}
          iconBg="rgba(234, 88, 12, 0.1)"
          iconColor="#ea580c"
        />
        <KPICard
          title="COMPLIANCE SLA"
          value="100%"
          change="Certified"
          changeType="positive"
          changePeriod="SOX • ISO 27001"
          icon={ShieldCheck}
          iconBg="rgba(147, 51, 234, 0.1)"
          iconColor="#9333ea"
        />
      </div>

      {/* 3. Filter Bar — 3 Dropdowns in ONE Horizontal Row */}
      <Card style={{ borderRadius: '12px', boxShadow: '0 1px 3px 0 rgba(0,0,0,0.02)' }}>
        <CardBody className="p-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 w-full">
            <div className="w-full">
              <Select
                value={categoryFilter}
                onChange={(e) => setCategoryFilter(e.target.value)}
                options={[
                  { label: 'All Categories', value: 'all' },
                  { label: 'Finance', value: 'Finance' },
                  { label: 'Sales', value: 'Sales' },
                  { label: 'Marketing', value: 'Marketing' },
                  { label: 'Operations', value: 'Operations' },
                  { label: 'Support', value: 'Support' },
                ]}
                style={{ height: '38px', fontSize: '13px', width: '100%' }}
              />
            </div>

            <div className="w-full">
              <Select
                value={userFilter}
                onChange={(e) => setUserFilter(e.target.value)}
                options={[
                  { label: 'All Users', value: 'all' },
                  { label: 'Alexander Wright', value: 'Alexander Wright' },
                  { label: 'Sarah Jenkins', value: 'Sarah Jenkins' },
                  { label: 'David Chen', value: 'David Chen' },
                ]}
                style={{ height: '38px', fontSize: '13px', width: '100%' }}
              />
            </div>

            <div className="w-full">
              <Select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                options={[
                  { label: 'All Statuses', value: 'all' },
                  { label: 'Approved', value: 'Approved' },
                  { label: 'Pending Review', value: 'Pending Review' },
                ]}
                style={{ height: '38px', fontSize: '13px', width: '100%' }}
              />
            </div>
          </div>
        </CardBody>
      </Card>

      {/* 4. Reports Table */}
      <Card style={{ borderRadius: '12px', overflow: 'hidden', boxShadow: '0 1px 3px 0 rgba(0,0,0,0.02)' }}>
        <CardBody className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableCell isHeader>Report Code</TableCell>
                <TableCell isHeader>Report Title</TableCell>
                <TableCell isHeader>Category</TableCell>
                <TableCell isHeader>Generated By</TableCell>
                <TableCell isHeader>Date</TableCell>
                <TableCell isHeader>Status</TableCell>
                <TableCell isHeader align="right">Actions</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredReports.map((rep) => (
                <TableRow key={rep.id}>
                  <TableCell><span className="font-mono text-xs text-tertiary">{rep.id}</span></TableCell>
                  <TableCell><span className="font-bold text-xs text-primary">{rep.title}</span></TableCell>
                  <TableCell><Badge variant="primary">{rep.category}</Badge></TableCell>
                  <TableCell><span className="text-xs text-secondary">{rep.user}</span></TableCell>
                  <TableCell><span className="text-xs text-tertiary">{rep.date}</span></TableCell>
                  <TableCell><Badge variant={rep.status === 'Approved' ? 'success' : 'warning'}>{rep.status}</Badge></TableCell>
                  <TableCell align="right">
                    <Button
                      variant="ghost"
                      size="sm"
                      icon={Download}
                      onClick={() => handleExportCSV(rep.title)}
                    >
                      Export CSV
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardBody>
      </Card>
    </div>
  );
};
