import React, { useState } from 'react';
import { FileText, Download, Filter as FilterIcon, Calendar, User } from 'lucide-react';
import { Breadcrumb, Button, Card, CardBody, Table, TableHeader, TableBody, TableRow, TableCell, Badge, Select, Input } from '../../components/ui';
import { useToast } from '../../context/ToastContext';

const reportsList = [
  { id: 'REP-101', title: 'Q1 Enterprise Revenue & MRR Audit', category: 'Finance', user: 'Alexander Wright', date: '2026-02-25', status: 'Approved', format: 'CSV / PDF' },
  { id: 'REP-102', title: 'Sales Pipeline & Opportunity Conversion', category: 'Sales', user: 'Sarah Jenkins', date: '2026-02-24', status: 'Approved', format: 'CSV' },
  { id: 'REP-103', title: 'Lead Source Attribution & ROI Analysis', category: 'Marketing', user: 'David Chen', date: '2026-02-22', status: 'Approved', format: 'CSV' },
  { id: 'REP-104', title: 'ERP Procurement & Inventory Valuation', category: 'Operations', user: 'Alexander Wright', date: '2026-02-20', status: 'Pending Review', format: 'CSV / PDF' },
  { id: 'REP-105', title: 'Customer Support SLA & CSAT Performance', category: 'Support', user: 'Elena Rostova', date: '2026-02-18', status: 'Approved', format: 'CSV' },
];

export const CrmReports = () => {
  const { addToast } = useToast();

  const [categoryFilter, setCategoryFilter] = useState('all');
  const [userFilter, setUserFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');

  const filteredReports = reportsList.filter((r) => {
    const matchCategory = categoryFilter === 'all' || r.category === categoryFilter;
    const matchUser = userFilter === 'all' || r.user === userFilter;
    const matchStatus = statusFilter === 'all' || r.status === statusFilter;
    return matchCategory && matchUser && matchStatus;
  });

  const handleExportCSV = (reportTitle) => {
    // Generate CSV string
    const csvHeader = 'Report ID,Title,Category,Generated By,Date,Status\n';
    const csvRows = filteredReports
      .map((r) => `"${r.id}","${r.title}","${r.category}","${r.user}","${r.date}","${r.status}"`)
      .join('\n');
    const csvContent = 'data:text/csv;charset=utf-8,' + encodeURIComponent(csvHeader + csvRows);

    const downloadLink = document.createElement('a');
    downloadLink.setAttribute('href', csvContent);
    downloadLink.setAttribute('download', `${reportTitle.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);

    addToast({ title: 'CSV Downloaded', message: `Exported ${reportTitle} to CSV format.`, type: 'success' });
  };

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <Breadcrumb items={[{ label: 'CRM nErgy' }, { label: 'Reports Hub' }]} />
          <h1 style={{ fontSize: 'var(--text-2xl)' }}>Enterprise Reports Repository</h1>
          <p className="text-xs text-secondary margin-0">
            Generate, filter, and export system audit reports in CSV and PDF formats
          </p>
        </div>

        <Button
          variant="primary"
          size="sm"
          icon={Download}
          onClick={() => handleExportCSV('All_CRM_Reports_Summary')}
        >
          Export All (CSV)
        </Button>
      </div>

      {/* Filter Bar */}
      <Card className="p-4 flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4">
        <div className="flex items-center gap-3 flex-wrap">
          <Select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            options={[
              { label: 'All Categories', value: 'all' },
              { label: 'Finance', value: 'Finance' },
              { label: 'Sales', value: 'Sales' },
              { label: 'Marketing', value: 'Marketing' },
              { label: 'Operations', value: 'Operations' },
              { label: 'Support', value: 'Support' },
            ]}
            style={{ height: '36px', fontSize: '13px' }}
          />

          <Select
            value={userFilter}
            onChange={(e) => setUserFilter(e.target.value)}
            options={[
              { label: 'All Users', value: 'all' },
              { label: 'Alexander Wright', value: 'Alexander Wright' },
              { label: 'Sarah Jenkins', value: 'Sarah Jenkins' },
              { label: 'David Chen', value: 'David Chen' },
            ]}
            style={{ height: '36px', fontSize: '13px' }}
          />

          <Select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            options={[
              { label: 'All Statuses', value: 'all' },
              { label: 'Approved', value: 'Approved' },
              { label: 'Pending Review', value: 'Pending Review' },
            ]}
            style={{ height: '36px', fontSize: '13px' }}
          />
        </div>
      </Card>

      {/* Reports Table */}
      <Card>
        <CardBody className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableCell isHeader>Report Code</TableCell>
                <TableCell isHeader>Report Title</TableCell>
                <TableCell isHeader>Category</TableCell>
                <TableCell isHeader>Generated By</TableCell>
                <TableCell isHeader>Date</TableCell>
                <TableCell isHeader>Status</TableCell>
                <TableCell isHeader align="right">Actions</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredReports.map((rep) => (
                <TableRow key={rep.id}>
                  <TableCell><span className="font-mono text-xs">{rep.id}</span></TableCell>
                  <TableCell><span className="font-semibold text-primary">{rep.title}</span></TableCell>
                  <TableCell><Badge variant="primary">{rep.category}</Badge></TableCell>
                  <TableCell>{rep.user}</TableCell>
                  <TableCell>{rep.date}</TableCell>
                  <TableCell><Badge variant={rep.status === 'Approved' ? 'success' : 'warning'}>{rep.status}</Badge></TableCell>
                  <TableCell align="right">
                    <Button
                      variant="ghost"
                      size="sm"
                      icon={Download}
                      onClick={() => handleExportCSV(rep.title)}
                    >
                      Export CSV
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardBody>
      </Card>
    </div>
  );
};
